### ISSUE TITLE
Apply corrections to the LaTeX document

### ISSUE THREAD

**Issue by marc7666** [marc7666/Bachelor-s-thesis#40]
- [x]  Change document type from "article" to "report" and instead of section make chapters
- [x] "Sections" to chapters.
- [x] Ceuta and Melilla → Switch the 0 and the 0% by NA.
- [x] Page 24 → Correct orthography ("neurona" "Qúe").
- [x] Join those paragraphs those only have 1 line. (If is possible and doesn't represent a grammatical mistake)
- [x] Newspaper articles: Make a comment of the authors' original publications. (Do not delete the newspaper articles)
https://arxiv.org/abs/2203.01944
https://www.nature.com/articles/s43856-022-00133-4

- [x] Explain differences between every model (hyperparameters, dataset, epochs)
- [x] Explain that Lime takes as important part black zones and emphasize that this should be corrected in future implementations.
- [x] Change the formula that represents the set of values of accuracy and batch_size by the domains.
- [x] Are not Annexes, are parts of a glossary.
- [x] Differentiate between bibliography and webgraphy.
- [x] Specify that all the webs have been accessed in 2023
- [x] Remove the page number of the index pages
